apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: vk-test
  labels:
    name: nginx
  annotations:
    omnideqname: eshop(app)->eshop(blueprint)->nginx(dep)->nginx(service)-loadbalancer(service-type)-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-port0
